{
    "th15_01": "Le vent de l'ouest rencontre celui de l'est",
    "th15_02": "Au-Dessus des Paysages de Verdure",
    "th15_03": "Altération Informatique des Réalités",
    "th15_04": "Champ de bataille où les hérétiques sont châtiés",
    "th15_05": "Magie Immaculée de l'Ordre du Beurre Doux",
    "th15_06": "Voyage Stellaire ~ A La Recherche Du Divin Sel",
    "th15_07": "Existense élusive ~ Abattre l'Ennemi !",
    "th15_08": "Les portes menant à des horizons tumultueux",
    "th15_09": "Le blizzard obstruant le soleil, se lève.",
    "th15_10": "Faraway Voyage of 380,000 Kilometers",
    "th15_11": "Pierrot of the Star-Spangled Banner",
    "th15_12": "The Sea that Reflects One's Home Planet",
    "th15_13": "Pure Furies ~ Whereabouts of the Heart",
    "th15_14": "A World of Nightmares Never Seen Before",
    "th15_15": "Pandemonic Planet",
    "th15_16": "The Moon as Seen from the Shrine",
    "th15_17": "The Space Shrine Maiden Returns Home",
}