{
	"2": "« Une jeune fille au QI d'or »",
	"5": "« Une jeune déesse au QI d'or »",
	"10": "Signe du gras « Butter Spark »",
	"23": "Illumination « Balles légendaires »",
	"26": "Signe primitif : « Être mono-neuronal »",
    "28": "Signe primitif : « Être bi-neuronal »",
    "29": "Signe primitif : « Neurone unique et infini »",
	"30": "Frontière de la sagesse : « Spirale autodestructrice »",
    "32": "Frontière de la sagesse : « Spirale destructrice incommensurable »",
	"34": "Signe du chaos : « Floraison imprévue »",
    "36": "Signe du chaos : « Floraison imprévue et fatale »",
    "37": "Signe du chaos : « Fleurs d'annihilation »",
    "38": "Signe de la lune : « Rêve lunatique outremer »",
	"58": "Douleur «Brûlure Lunaire»",
    "60": "Désespoir «Duplicité de la Fille Lunatique»",
	"62": "Signe mental : « Obsession »",
    "64": "Signe mental : « Rupture »",
	"66": "Illusion d'optique : « 7ème art »",
	"69": "Illusion magique : « Rokkenjima »",
    "70": "Puissance max : « Moon Breaker »",
	"74": "« Point de non retour »",
    "76": "« La prêtresse du crépuscule »",
    "78": "Signe du Beurre Doux \" je sais pas\" ",
}