{
    "58": "Douleur ”Brûlure Lunaire”",
    "60": "Douleur ”Brûlure Lunaire”",
    "62": "Douleur ”Brûlure Lunaire”",
    "64": "Désespoir ”Duplicité de la Fille Lunatique”",
    "66": "Feux de l'Enfer : « Frôlement infernal »",
    "69": "Feux de l'Enfer : « Secrets infernaux du frôlement »",
    "70": "Enfer : « Abysses rayées »",
    "74": "« Faux Apollo »",
    "76": "« La théorie du complot d'Apollo »",
    "78": "Signe du Beurre Doux \" je sais pas\" ",
    "82": "« Lys au dessein meurtrier »",
    "86": "« Monde primitif de l'esprit divin »",
    "88": "« Monde contemporain de l'esprit divin »",
    "90": "« Étoile engourdie et frémissante »",
    "94": "« Folie immaculée »",
    "98": "« Impureté débordante »",
    "101": "« Purification de la souillure terrienne »",
    "102": "Signe de la pureté : « Un enfer de purs projectiles »",
    "104": "Signe de la pureté : « Un enfer au danmaku immaculé »",
    "106": "Papillon : « Supplantation de papillons »",
    "107": "Super-express : « L'express des rêves »",
    "108": "Rêve rampant : « Projectiles furtifs »",
    "109": "Autres Mondes : « À la tombée de la nuit »",
    "110": "Terre : « Impureté malfaisante du corps »",
    "111": "Lune : « Le miroir reflétant Apollo »",
    "112": "« Un simple danmaku pour piéger un rat acculé »",
    "113": "Autres Mondes : « Danmaku non idéal de l'Enfer »",
    "114": "Terre : « Pluie chutant en Enfer »",
    "115": "Lune : « Impact lunatique »",
    "116": "« Un danmaku immaculé pour assassiner un humain »",
    "117": "« La rhapsodie trinitaire »",
    "118": "« Premier et ultime danmaku sans nom »"
}