{
    "0": "Balle désastreuse : « Frappe rapide »",
    "2": "Signe du projectile : « Tir de l'aigle »",
    "5": "Signe du projectile : « Le rapace s'est fait abattre »",
    "10": "Signe du lapin : « Dango à la fraise »",
    "12": "Signe du lapin : « Dango aux deux baies »",
    "14": "Signe du lapin : « Influence du dango »",
    "18": "Tsukimi : « Pleine lune de septembre »",
    "21": "Saké du Tsukimi : « Septembre lunatique »",
    "22": "Signe du rêve : « Cauchemar écarlate »",
    "24": "Signe du rêve : « Oppressant cauchemar écarlate »",
    "26": "Signe du rêve : « Rêve de mélancolie indigo »",
    "28": "Signe du rêve : « Triple rêve de mélancolie indigo »",
    "29": "Signe du rêve : « Rêve d'une mélancolie éternelle »",
    "30": "Signe du rêve : « Fantasme vert tilleul »",
    "32": "Signe du rêve : « Fantasme méandreux vert tilleul »",
    "34": "Signe du rêve : « Attrape-rêves »",
    "36": "Signe du rêve : « Attrape-rêves azuré »",
    "37": "Signe du rêve : « Égaré dans un rêve »",
    "38": "Signe de la lune : « Rêve lunatique outremer »",
    "42": "Signe de l'orbe : « Malédiction des corbeaux agités »",
    "44": "Signe de l'orbe : « Malédiction inversée des corbeaux agités »",
    "45": "Signe de l'orbe : « Double malédiction des corbeaux agités »",
    "46": "Signe de l'orbe : « Mines détectant les corps impurs »",
    "48": "Signe de l'orbe : « Mines détectant les corps impurs : améliorées »",
    "50": "Signe de l'orbe : « Couronne divine de projectiles »",
    "52": "Signe de l'orbe : « L'étincelante couronne divine de projectiles »",
    "54": "« Le héron blanc à une aile »",
    "58": "Signe de la prison : « Éclipse infernale »",
    "60": "Signe de la prison : « Éclipse de l'Enfer »",
    "62": "Signe de la prison : « Un éclair et des bandes »",
    "64": "Signe de la prison : « Des étoiles et des bandes »",
    "66": "Feux de l'Enfer : « Frôlement infernal »",
    "69": "Feux de l'Enfer : « Secrets infernaux du frôlement »",
    "70": "Enfer : « Abysses rayées »",
    "74": "« Faux Apollo »",
    "76": "« La théorie du complot d'Apollo »",
    "78": "Signe du Beurre Doux \" je sais pas\" ",
    "82": "« Lys au dessein meurtrier »",
    "86": "« Monde primitif de l'esprit divin »",
    "88": "« Monde contemporain de l'esprit divin »",
    "90": "« Étoile engourdie et frémissante »",
    "94": "« Folie immaculée »",
    "98": "« Impureté débordante »",
    "101": "« Purification de la souillure terrienne »",
    "102": "Signe de la pureté : « Un enfer de purs projectiles »",
    "104": "Signe de la pureté : « Un enfer au danmaku immaculé »",
    "106": "Papillon : « Supplantation de papillons »",
    "107": "Super-express : « L'express des rêves »",
    "108": "Rêve rampant : « Projectiles furtifs »",
    "109": "Autres Mondes : « À la tombée de la nuit »",
    "110": "Terre : « Impureté malfaisante du corps »",
    "111": "Lune : « Le miroir reflétant Apollo »",
    "112": "« Un simple danmaku pour piéger un rat acculé »",
    "113": "Autres Mondes : « Danmaku non idéal de l'Enfer »",
    "114": "Terre : « Pluie chutant en Enfer »",
    "115": "Lune : « Impact lunatique »",
    "116": "« Un danmaku immaculé pour assassiner un humain »",
    "117": "« La rhapsodie trinitaire »",
    "118": "« Premier et ultime danmaku sans nom »"
}